import javax.swing.ImageIcon;

public class Imagejpgs {
    public static ImageIcon herouIcon = new ImageIcon("jpgs/herou.png");
	public static ImageIcon herolIcon = new ImageIcon("jpgs/herol.png");
	public static ImageIcon herorIcon = new ImageIcon("jpgs/heror.png");
	public static ImageIcon herodIcon = new ImageIcon("jpgs/herod.png");
	public static ImageIcon groundIcon = new ImageIcon("jpgs/ground.png");
	public static ImageIcon wallIcon = new ImageIcon("jpgs/wall.png");
	public static ImageIcon upIcon = new ImageIcon("jpgs/up.png");
	public static ImageIcon downIcon = new ImageIcon("jpgs/down.png");
	public static ImageIcon redkeyIcon = new ImageIcon("jpgs/redkey.png");
	public static ImageIcon reddoorIcon = new ImageIcon("jpgs/reddoor.png");
	public static ImageIcon yellowkeyIcon = new ImageIcon("jpgs/yellowkey.png");
	public static ImageIcon yellowdoorIcon = new ImageIcon("jpgs/yellowdoor.png");
	public static ImageIcon greenslmIcon = new ImageIcon("jpgs/greenslm.png");
	public static ImageIcon redslmIcon = new ImageIcon("jpgs/redslm.png");
	public static ImageIcon smallbfIcon = new ImageIcon("jpgs/smallbf.png");
	public static ImageIcon specialdoorIcon = new ImageIcon("jpgs/specialdoor.png");
	public static ImageIcon redstoneIcon = new ImageIcon("jpgs/redstone.png");
	public static ImageIcon bluestoneIcon = new ImageIcon("jpgs/bluestone.png");
	public static ImageIcon redbottleIcon = new ImageIcon("jpgs/redbottle.png");
	public static ImageIcon bluebottleIcon = new ImageIcon("jpgs/bluebottle.png");
    public static ImageIcon emptyIcon = new ImageIcon("jpgs/airwall.png");
	public static ImageIcon xbgIcon = new ImageIcon("jpgs/xbg.jpg");
	public static ImageIcon breakwallIcon = new ImageIcon("jpgs/breakwall.png");
	public static ImageIcon cflyIcon = new ImageIcon("jpgs/cfly.png");
	public static ImageIcon HPIcon = new ImageIcon("jpgs/HP.png");
	public static ImageIcon atkIcon = new ImageIcon("jpgs/atk.png");
	public static ImageIcon defIcon = new ImageIcon("jpgs/def.png");
	public static ImageIcon blackslmIcon = new ImageIcon("jpgs/blackslm.png");
	public static ImageIcon bigslmIcon = new ImageIcon("jpgs/bigslm.png");
	public static ImageIcon bigbfIcon = new ImageIcon("jpgs/bigbf.png");
	public static ImageIcon bigklIcon = new ImageIcon("jpgs/bigkl.png");
	public static ImageIcon blackkingIcon = new ImageIcon("jpgs/blackking.png");
	public static ImageIcon blackqsIcon = new ImageIcon("jpgs/blackqs.png");
	public static ImageIcon yellowbottleIcon = new ImageIcon("jpgs/yellowbottle.png");
	public static ImageIcon bossIcon = new ImageIcon("jpgs/Boss.png");
	public static ImageIcon redbfIcon = new ImageIcon("jpgs/redbf.png");
	public static ImageIcon redqsIcon = new ImageIcon("jpgs/redqs.png");
	public static ImageIcon shourenIcon = new ImageIcon("jpgs/shouren.png");
	public static ImageIcon smallklIcon = new ImageIcon("jpgs/smallkl.png");
}
